name: Check Script

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checks
        run: |
          php update-manager/update-manager.php script-check tr || exit 1